### ISSUE TITLE
Installation notes 

### ISSUE THREAD

**Issue by jakobklein** [fgerschau/periodic-background-sync-example#1]
Readme says to "Run npm start and go to http://localhost:5000."
Please add a hint that you need to install the PWA to get the permission for periodic updates granted.
Took me a while. 

Otherwise great example, thx!

**Comment by fgerschau** [comment]
@jakobklein thanks for letting me know.

I created this repository for [a tutorial](https://felixgerschau.com/periodic-background-sync-explained/) I wrote on the topic. It probably makes sense to add a link to the readme as well :smile:
